name: updatable_widget
description: Automatically Updatable Widget
version: 0.0.2
homepage: https://github.com/rehmnabdul/updatable-widget

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
